project 'SignalR.Client.ObjC Example.xcodeproj'
workspace '../SignalR.Client.ObjC'

use_frameworks!

pod 'SignalR-ObjC', :path => '..'

target "OS X Example" do
    platform :osx, '10.9'
end

target "iOS Example" do
    platform :ios, '9.0'
end
